---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: backend

spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - image: hasandardashti/chat_backend:latest
          imagePullPolicy: IfNotPresent
          name: img-backend
          ports:
            - hostPort: 8000
              protocol: TCP
              containerPort: 8000
          resources:
            limits:
              cpu: "0.1"
              ephemeral-storage: 1G
              memory: 200M
            requests:
              cpu: "0.1"
              ephemeral-storage: 1G
              memory: 200M

---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  labels:
    app: backend

spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
