---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: frontend
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - image: hasandardashti/chat_front:latest
          imagePullPolicy: IfNotPresent
          name: frontend
          ports:
            - containerPort: 8888
              hostPort: 8888
              protocol: TCP
          resources:
            limits:
              cpu: "0.1"
              ephemeral-storage: 1G
              memory: 200M
            requests:
              cpu: "0.1"
              ephemeral-storage: 1G
              memory: 200M
          env:
            - name: VITE_BACK_END_ADDRESS
              valueFrom:
                configMapKeyRef:
                  name: app-config-map
                  key: backend_url
            - name: VITE_BACK_END_PORT
              valueFrom:
                configMapKeyRef:
                  name: app-config-map
                  key: backend_port

---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  labels:
    app: frontend
spec:
  ports:
    - name: "8888"
      port: 8888
      targetPort: 8888
  selector:
    app: frontend
  
