---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-conf
  template:
    metadata:
      labels:
        app: nginx-conf
    spec:
      containers:
        - name: nginx-conf
          image: hasandardashti/nginx-conf:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          resources:
            limits:
              cpu: "0.1"
              ephemeral-storage: 1G
              memory: 200M
            requests:
              cpu: "0.1"
              ephemeral-storage: 1G
              memory: 200M
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    app: nginx-conf
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80

  type: LoadBalancer