apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: backend-image:latest  # Replace with your image name
          ports:
            - containerPort: 5000
          env:
            - name: BACKEND_URL
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: BACKEND_URL
            - name: API_KEY
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: API_KEY
          volumeMounts:
            - mountPath: /data
              name: backend-storage
      volumes:
        - name: backend-storage
          persistentVolumeClaim:
            claimName: backend-pvc
